### ISSUE TITLE
Fieldset to group related elements

### ISSUE THREAD

**Issue by edmondchuc** [AGLDWG/PID-Allocations-Catalogue#2]
Current suggestion made by Simon Cox.

Require a fieldset module in Drupal 8 to group related elements for better clarity in creating a new CatalogRecord.

Elements suggested for grouping:

- RDF File

- Requested URI

In general, each section should have a fieldset to better structure the page.

**Comment by nicholascar** [comment]
Should be RDF File or Access URI: these are for a resource to be accessed for review. Requested URI is of the PID to be assigned.

**Comment by nicholascar** [comment]
I have added a Fieldset to group the now renamed fields of Resource RDF File and Resource Access URI together when a new entry is being created. It doesn't seem to make too much difference though, given the cluttered nature of the Drupal form.
